---
# After you have replaced all the __CHANGE_ME__ values in this file, you need to
# run `make auth` to setup the Auth.
tre_id: tr58dev
location: westus2
management:
  mgmt_resource_group_name: tr58dev
  mgmt_storage_account_name: tr58dev
  terraform_state_container_name: tfstate
  acr_name: az58trdv
  # Azure Resource Manager credentials used for CI/CD pipelines
  arm_subscription_id: 08ea814c-214a-4394-a67c-d4ec7458d07e
  # If you want to override the currently signed in credentials
  # You would do this if running commands like `make terraform-install DIR=./templates/workspaces/base`
  # arm_tenant_id: __CHANGE_ME__
  # arm_client_id: __CHANGE_ME__
  # arm_client_secret: __CHANGE_ME__
tre:
  # If your local machine/build agent cannot get the public IP
  # address from https://ipecho.net/plain, then you can circumvent
  # this by setting this Environment variable. This blockage can
  # be caused by trying to deploy TRE in an Office environment where
  # this website is blocked. This value is the public facing IP
  # address of the deploying machine.
  # public_deployment_ip_address: __CHANGE_ME__
  core_address_space: 10.1.0.0/22
  tre_address_space: 10.0.0.0/12
  core_app_service_plan_sku: P1v2
  resource_processor_vmss_sku: Standard_B2s
  enable_swagger: true
  enable_airlock_malware_scanning: false
  # TODO: move to RP default with https://github.com/microsoft/AzureTRE/issues/2948
  workspace_app_service_plan_sku: P1v2
  # The TRE Web UI is deployed by default.
  # Uncomment the following to disable deployment of the Web UI.
  # deploy_ui: false
authentication:
  aad_tenant_id: 2052f6a0-55ba-49c0-94b6-42c76c208091
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to false will:
  # create an identity with `Application.ReadWrite.OwnedBy`.
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to true will:
  # create an identity with `Application.ReadWrite.All` and `Directory.Read.All`.
  # When this is true, create Workspaces will also create an AAD Application automatically.
  # When this is false, the AAD Application will need creating manually.
  auto_workspace_app_registration: true
  # Setting AUTO_WORKSPACE_GROUP_CREATION to true will create an identity with `Group.ReadWrite.All`
  auto_workspace_group_creation: false
  application_admin_client_id: 041cb3a1-0174-4257-995b-52c304b29e6f
  application_admin_client_secret: dKJ8Q~KJvU2EBaDR6lUVAp~SoXIQmnSE9VDtvae9
  test_account_client_id: 4ec35e31-2d41-4b8e-8d44-4744bf74934a
  test_account_client_secret: emF8Q~IQ85hX~M7zAaqG0y6hKT7UF_gW-ONzDbaM
  api_client_id: 16d89c76-8e71-4cb8-954e-55f97c009969
  api_client_secret: MDW8Q~byKnHSBxkqtWHsvlL7v_5ME_CKB8GxKcD8
  swagger_ui_client_id: 4beb66e0-188d-4851-af00-950e73cc5aef
resource_processor:
  # The number of processes to start in the resource processor VMSS image
  resource_processor_number_processes_per_instance: 5
# This setting provides a way to pass environment values to the resource processor
# to use as a source of bundle parameter values
# For example, to specify your image_gallery_id for use in VM user resources with custom VM images:
# yamllint disable-line rule:line-length
#  rp_bundle_values: '{"custom_key_1":"custom_value_1","image_gallery_id":"/subscriptions/<subscription-id>/resourceGroups/<your-rg>/providers/Microsoft.Compute/galleries/<your-gallery-name>"}'
developer_settings:
# Locks will not be added to stateful resources so they can be easily removed
# stateful_resources_locked: false

# If you want to use TRE_URL to point to your local TRE API instance,
# uncomment and set this variable
#   tre_url: __CHANGE_ME__

# This setting will enable your local machine to be able to
# communicate with Service Bus and Cosmos. It will also allow deploying
# the base workspace.
#  enable_local_debugging: true

# Used by the API and Resource processor application to change log level
#  debug: true
